---
- name: " Installing node-exporter"
  unarchive:
    src: "{{ url }}"
    dest: "/opt/"
    remote_src: true

- name: "Copying the files"
  copy:
    src: "/opt/node_exporter-{{ version }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: true
    owner: root
    group: root
    mode: 0755

- name: "Creating systemd service for node-exporter"
  template:
    src: "node_exporter.service.tmpl"
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0600


- name: "configure systemd"
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: node_exporter.service
